const products = {
  mentor: [
    "ACCESS TO STARTUPS",
    "DISCOVERABILITY",
    "SUPPORT SERVICES",
    "COMMUNITY",
    "PATCH",
    "VIBE",
    "RAAYA",
    "NEWS & ARTICLES",
    "DISCOVER",
    "EVENTS",
    "CIRCLES",
    "MESSAGES & NOTIFICATIONS",
  ],
  investor: [
    "PATCH",
    "VIBE",
    "DASHBOARD",
    "COMMUNITY",
    "CIRCLES",
    "RAAYA",
    "DISCOVER",
    "PROFILE",
    "NEWS & ARTICLES",
    "EVENTS",
    "SEARCH ENGINE",
    "MESSAGES & NOTIFICATIONS",
  ],
  founder: [
    "MENTOR",
    "COMMUNITY",
    "PATCH",
    "VIBE",
    "KNOWLEDGE",
    "FUNDING-APPLY",
    "EVENTS",
    "TOOLS",
    "JOBS",
    "CIRCLES",
    "RAAYA",
    "NEWS & ARTICLES",
    "SEARCH ENGINE",
    "INVESTOR FINDER",
    "DISCOVER",
    "MESSAGES & NOTIFICATIONS",
  ],
  individual: [
    "MENTOR",
    "COMMUNITY",
    "PATCH",
    "VIBE",
    "KNOWLEDGE",
    "FUNDING-APPLY",
    "EVENTS",
    "TOOLS",
    "JOBS",
    "CIRCLES",
    "RAAYA",
    "NEWS & ARTICLES",
    "SEARCH ENGINE",
    "INVESTOR FINDER",
    "DISCOVER",
    "MESSAGES & NOTIFICATIONS",
  ],
  professionals: [
    "COMMUNITY",
    "PATCH",
    "VIBE",
    "KNOWLEDGE",
    "EVENTS",
    "JOBS",
    "CIRCLES",
    "DISCOVER",
    "NEWS & ARTICLES",
    "SEARCH ENGINE",
    "MESSAGES & NOTIFICATIONS",
  ],
  serviceproviders: [
    "ACCESS TO STARTUPS",
    "RAAYA",
    "MESSAGES & NOTIFICATIONS",
    "DASHBOARD",
    "PREMIUM",
  ],
  ib: [
    "SUPPORT SERVICES-CLOSING",
    "DISCOVERABILITY OVER THE PLATFORM- PLATFORM FEES",
    "DASHBOARD",
  ],
};


export default products;